title: Applied AI for Cybersecurity
description: Level 6 course site with syllabus, weekly lectures, labs, assessment, and references
url: "https://mo574216.github.io"
baseurl: "/applied-ai-for-cybersecurity"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: light
